M48
; DRILL file {KiCad (6.0.2)} date Fri Aug  4 12:44:49 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-04T12:44:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.300
%
G90
G05
T1
X107.858Y-124.9
T2
X107.858Y-120.4
T3
X62.5Y-68.0
X62.5Y-123.5
X105.85Y-93.65
X144.0Y-68.0
X144.0Y-123.5
T0
M30
